I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    call screen Map1()
  File "renpy/common/000statements.rpy", line 531, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/common/00action_data.rpy", line 79, in get_selected
    return __get_field(self.object, self.field, self.kind) == self.value
  File "renpy/common/00action_data.rpy", line 39, in _m1_00action_data__get_field
    raise NameError("The {} {} does not exist.".format(kind, name))
NameError: The variable map_xoffset_list[map] does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script
    call screen Map1()
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\ast.py", line 1949, in execute
    self.call("execute")
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\ast.py", line 1937, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\statements.py", line 277, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 531, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\exports.py", line 2905, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\core.py", line 3094, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\screen.py", line 434, in visit_all
    self.child.visit_all(callback, seen=None)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\core.py", line 543, in visit_all
    callback(self)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\core.py", line 3094, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\behavior.py", line 857, in per_interact
    if self.is_selected():
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\behavior.py", line 845, in is_selected
    return is_selected(self.action)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\behavior.py", line 391, in is_selected
    return action.get_selected()
  File "renpy/common/00action_data.rpy", line 79, in get_selected
    return __get_field(self.object, self.field, self.kind) == self.value
  File "renpy/common/00action_data.rpy", line 39, in _m1_00action_data__get_field
    raise NameError("The {} {} does not exist.".format(kind, name))
NameError: The variable map_xoffset_list[map] does not exist.

Windows-8-6.2.9200
Ren'Py 7.3.4.596
Demo1979 1.0
Thu Oct 17 18:22:00 2019
